### PR TITLE
superfluous xtime

### PR DESCRIPTION
**Pull request by conorpp**

### CODE REVIEW

**Comment by kokke** [comment]
Thank you very much for pointing out this issue.

Implementing this change will actually increase code size with my compilers, for both ARM and x86_64.
Removing the last call to xtime() seem to spoil some vectorization-optimization that the compiler performs.

**Comment by kosciCZ** [comment]
I'd say this would be worthy of a comment in the code, that the last line is redundant and there for compiler optimization.

**Comment by kosciCZ** [comment]
Nice! Thanks.

**Comment by Legorooj** [comment]
This can be closed, can it not @kokke?

**Comment by kokke** [comment]
Hi @Legorooj 

Yes this issue can be closed.

There is a comment in the code, pointing to this issue - thanks for pointing it out :)

**Comment by Legorooj** [comment]
@kokke you need to do it :-) only repo owners and people you've given permission to can close PRs/Issues

**Pull request closed without merging**
