### PR TITLE
Conan recipe

### PR DESCRIPTION
**Pull request by torfinnberset**
Hey, I've started adding my packages to conan.io lately, and I wanted to try to contribute a recipe for tiny-AES-c. In the process, I've also added a CMake file to make the conan integration easier.

Usage:

```
     conan create . conan/stable
```

This should compile the library and run the tests. If you want, you can upload the recipe to conan-center following the instructions here: https://docs.conan.io/en/latest/uploading_packages/bintray/conan_center_guide.html

I've set the version number to `1.0.0` in `conanfile.py` but there's not yet any official versioning of this library. Perhaps if you accept the recipe, you can also do a proper release on GitHub and tag it `v1.0.0`.

### CODE REVIEW

**Comment by kokke** [comment]
Hi Torfinn, thanks for taking an interest in this project :)

I am not familiar with conan.io, but I have accepted a PR for something related to platform.io (which I am also not familiar with) in #94, so I think I should accept this as well. 

If any questions / issues arise regarding conan.io, I will be mentioning your username and pointing to this PR. Are you okay with that?

Thanks for contributing :)

**Comment by torfinnberset** [comment]
Hey @kokke, yes I'm fine with being the package maintainer! It will be my first released package though, but I'm happy to learn the process.

**Comment by torfinnberset** [comment]
@kokke, do you want me to submit the package to conan-central? If so, do you mind making a v1.0.0 release of the library? I prefer not having to refer to the latest git hash if possible 😄

**Comment by kokke** [comment]
@torfinnberset if you would handle the conan submission, I would be very pleased :)

I have never tried releasing anything on github, I mostly use it to showcase code and get great feedback.
I hope I've done it correctly, please check out https://github.com/kokke/tiny-AES-c/releases/tag/v1.0.0

**Comment by torfinnberset** [comment]
@kokke perfect! I'll have a look in the coming week on getting it submitted. Will keep you posted :) Congrats on the 1.0 milestone ;)

**Comment by kokke** [comment]
Haha thank you very much :D Only took me ~6.5 years to get a first release

**Comment by DmitryDemidov80** [comment]
Will the project be supported further?

**Comment by kokke** [comment]
Hi @DmitryDemidov80 that depends on what kind of support we are talking about :)

I actively support users reporting problems (see the [issues-section](https://github.com/kokke/tiny-AES-c/issues)), and sometimes I even accept a PR.

I think the project is fairly stable and should not need to change much. So you won't see many feature additions or radical changes in the near future.

I would however like to add GCM some day, but haven't had the time/energy/motivation to do so.

**Comment by DamonHD** [comment]
If you do get there, maybe OTAESGCM can be a source of GCM implementation to help with that...

Rgds

Damon

**Comment by kokke** [comment]
Haha Hi @DamonHD - I was SO close to mentioning the OpenTRV project and you, when I wrote about GCM being on the wishlist :D

Thank you for your vigilance, as always :)

**Pull request merged**
