### PR TITLE
Made the key const, since it could be in ROM. Made 'Multiply' a function...

### PR DESCRIPTION
**Pull request by jcallan**
Hi Kokke, thanks for writing such a small AES! I have made a few little changes which (hopefully) improve it even more. When I compile it using the ARM Keil compiler it now only uses 1268 bytes total.
Jon.

### CODE REVIEW

**Comment by bnorbs** [comment]
Hi Kokke,
thanks for the good work.
I am going to use it in energia and for msp430G2553. This device has only 512 Bytes RAM. Therefore I had to try using the same buffer for input and output (encrypt // decrypt still to test) and it worked. I saw that you anyway copy input to output at an early stage. I wonder if it would be possible to change the code and everywhere use only one buffer. Perhaps one could also eliminate the static array state and save 16 more bytes ( :-) )?

Btw, I only use cbc, because ebc is almost every time prone to replay or chosen plaintext (and more) attacks. Therefore I was disappointed by TI's solution (which was mentioned above).

Thanks again, for the good job.

**Comment by MorgothCreator** [comment]
Great work, I compiled for atmega, atxmega E5 series, it works perfectly.

**Comment by skater-boy** [comment]
Just a note as reference for others.
Added a `#define MULTIPLY_AS_A_FUNCTION 1` and tested on Cortex M0+, gcc compiler and -Os code optimization.
Code reduction is negligible.

**Comment by tecsantoshkumar** [comment]
hello friends,

any one help me for tiny-AES128CBC library how to used in this library salt and iteration count.

**Pull request closed without merging**
